name: Backend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            NODE_BIN="/home/praveenbesetti09/.nvm/versions/node/v24.14.0/bin"
            PROJECT_DIR="/var/www/backend"

            sudo chown -R praveenbesetti09:praveenbesetti09 $PROJECT_DIR
            git config --global --add safe.directory $PROJECT_DIR
            cd $PROJECT_DIR

            # If .git folder is missing, re-clone/init
            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://github.com/praveenbesetti/Survey-Backend.git
            fi

            # Force sync
            git fetch --all
            git reset --hard origin/main
            git clean -fd

            echo "${{ secrets.ENV_FILE_CONTENT }}" | sudo tee .env > /dev/null
            
            # Use 'node' to run npm/pm2 to avoid "Permission denied"
            $NODE_BIN/node $NODE_BIN/npm install --production
            $NODE_BIN/node $NODE_BIN/pm2 restart backend-api --update-env || $NODE_BIN/node $NODE_BIN/pm2 start server.js --name "backend-api"
            
            sudo systemctl reload nginx